import { ISchema } from 'xml-schema2/lib/types';
export declare const DATE: ISchema;
export declare const AUTHOR: ISchema;
export declare const PRICE: ISchema;
export declare const LINK: ISchema;
export declare const CATEGORY: ISchema;
export declare const CONTENT_BASE: ISchema;
export declare const CONTENT: ISchema;
export declare const ENTRY: ISchema;
export declare const FEED: ISchema;
export default FEED;
